<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DictateAnywhere.Audio</RootNamespace>
    <AssemblyName>DictateAnywhere.Audio</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DictateAnywhere.Core\DictateAnywhere.Core.csproj" />
    <ProjectReference Include="..\DictateAnywhere.Platform.Windows\DictateAnywhere.Platform.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" />
  </ItemGroup>
</Project>
